In [1]:
import tensorflow as tf

In [2]:
import sparse_convolution as sc

In [3]:
test = sc.EncoderDecoderStack([]);

In [4]:
test2 = sc.RandomSparseConv2D(10, 4, 1, 3, kernel_size = (2, 2), use_bias = True);

In [8]:
testin = tf.ones(dtype=tf.float32, shape = [1, 5, 5, 3]);
with tf.GradientTape(persistent=True) as tape:
    testout = test2.encoder(testin);
print('');
print('');
print('Output: ');
print(testout);
print('Weight: ');
w = test2._encoder.convlayers[1].weights[0];
print(w);
print('Grad: ');
grad_b = tape.jacobian(testout, w, experimental_use_pfor = False);
print(grad_b);

W0902 16:48:56.332066  3904 deprecation.py:323] From c:\programme\python36\lib\site-packages\tensorflow_core\python\ops\array_grad.py:502: _EagerTensorBase.cpu (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.identity instead.


Blocks: 
tf.Tensor(
[[[8]
  [5]
  [0]]

 [[9]
  [1]
  [0]]

 [[3]
  [1]
  [6]]

 [[7]
  [4]
  [2]]], shape=(4, 3, 1), dtype=int32)
Non-Scattered outputs:
tf.Tensor(
[[[[[ 0.45029563  0.45029563  0.45029563  0.45029563]
    [ 0.45029563  0.45029563  0.45029563  0.45029563]
    [ 0.45029563  0.45029563  0.45029563  0.45029563]
    [ 0.45029563  0.45029563  0.45029563  0.45029563]]]


  [[[-0.14150953 -0.14150953 -0.14150953 -0.14150953]
    [-0.14150953 -0.14150953 -0.14150953 -0.14150953]
    [-0.14150953 -0.14150953 -0.14150953 -0.14150953]
    [-0.14150953 -0.14150953 -0.14150953 -0.14150953]]]


  [[[ 0.43384066  0.43384066  0.43384066  0.43384066]
    [ 0.43384066  0.43384066  0.43384066  0.43384066]
    [ 0.43384066  0.43384066  0.43384066  0.43384066]
    [ 0.43384066  0.43384066  0.43384066  0.43384066]]]]



 [[[[ 1.25911     1.25911     1.25911     1.25911   ]
    [ 1.25911     1.25911     1.25911     1.25911   ]
    [ 1.25911     1.25911     1.25911     1.25911   ]
    [ 1.259